### ISSUE TITLE
Feature request:  Add an option to set a default value.

### ISSUE THREAD

**Issue by clawall** [edudavid/json-map-transform#1]
When the transform function (user-defined) returns undefined, null or an empty String, the result is an empty object. 

It would be great if we could have a default value option that would be set if any of these is returned.

**Comment by edudavid** [comment]
@clawall thank you for the suggestion.

The default options is now available. Can you test it please?

**Comment by clawall** [comment]
It worked greatly, @edudavid! Thanks for the quick action!
