### ISSUE TITLE
Returning undefined for false or 0

### ISSUE THREAD

**Issue by csch0** [edudavid/json-map-transform#2]
If you have a boolean variable with false, or an Integer with 0, it will be undefined.

https://github.com/edudavid/json-map-transform/blob/2b454ca039d817df5959a1ea093e6bb22179851b/lib/utils/objectHandler.js#L17

I think the problem is here, it should be: 

`value = (value && value[subPath] !== undefined) ? value[subPath] : undefined;`

And further here the logic needs to be changed:

https://github.com/edudavid/json-map-transform/blob/2b454ca039d817df5959a1ea093e6bb22179851b/lib/jsonMapTransform.js#L9

**Comment by edudavid** [comment]
Hello @csch0 ,

Thank you for reporting. It is fixed and a new version is available at npm.
Please let me know if its working as you expected.
